### ISSUE TITLE
Maize ChIAPET data 

### ISSUE THREAD

**Issue by GenXu1** [wh90999/ChIAPoP#3]
Hi Dr. Huang,
Can I use ChIAPOP work on maize ChIA-PET data? For the usage of parameter “ref.genome” in "pop.pipeline" function, it seems maize genome is not acceptable.

Thank you！

**Comment by niuleon** [comment]
Hi Gen,

The reason is that we use the GenomeInfoDb package and it seems that it does not support the maize genome yet, see the section for fetchExtendedChromInfoFromUCSC in their manual:

https://bioconductor.org/packages/release/bioc/manuals/GenomeInfoDb/man/GenomeInfoDb.pdf

If they can update their package to support maize genome, e.g., zm3, then you can use our package to analyze your data.
